export enum TargetMethod {
    PBAoE = "PBAoE",
    ThrownItem = "ThrownItem",
    GroundPound = "GroundPound",
    GroundPoundHB = "GroundPoundHB",
    GroundPoundRecover = "GroundPoundRecover",
    Smash = "Smash",
    SmashRelease = "SmashRelease",
    GroundCheck = "GroundCheck",
    SmashReleaseGroundCheck = "SmashReleaseGroundCheck",
    Grab = "Grab",
    GrabRelease = "GrabRelease",
    SmashGrabRelease = "SmashGrabRelease",
    SmashReleaseGrabHit = "SmashReleaseGrabHit",
    Nobody = "Nobody",
    Ranged = "Ranged",
    RangedAoE = "RangedAoE",
    SmashReleaseRangedAoE = "SmashReleaseRangedAoE",
    MeteorPound = "MeteorPound",
    MeteorPoundRelease = "MeteorPoundRelease",
    Path = "Path",
    PathExplosion = "PathExplosion",
    SmashReleasePath = "SmashReleasePath",
    SmashReleasePathExplosion = "SmashReleasePathExplosion",
    Collider = "Collider",
    SmashReleaseCollider = "SmashReleaseCollider",
    Stance = "Stance",
    Taunt = "Taunt",
    TauntRelease = "TauntRelease"
    //TODO: Fully document every possible value
}